name: Compile ESP8266



on:
  push:
    branches:
      - master
      - dev
      - dev_auto_compile

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: "arduino:avr:uno"

          sketch-paths: |
            - examples/aaa/aaa.ino