name: Compile ESP8266



on:
  push:
    branches:
      - master
      - dev
      - dev_auto_compile

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile ESP8266
        uses: arduino/compile-sketches@v1
        with:
          fqbn: "arduino:avr:uno"
          libraries: |
            - name: Servo
            - name: Stepper
              version: 1.1.3
          sketch-paths: |
            - examples/aaa